[book]
authors = ["Gizmo Team"]
language = "en"
multilingual = false
src = "src"
title = "Gizmo Guide"

[output.html]

[output.pdf]
optional = true

[preprocessor.callouts]

[preprocessor.d2-go]
layout = "elk"
theme_id = 0
